name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  tests-on-phpunit-9:
    runs-on: "ubuntu-latest"
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        php:
          - '8.0'
          - 8.1
          - 8.2
          - 8.3
        phpunit:
          - "9.x"
        dependencies:
          - "highest"
          - "lowest"
        experimental:
          - false

    name: PHP:${{ matrix.php }} / PHPUnit:${{ matrix.phpunit }} ${{ matrix.dependencies == 'highest' && '⬆️' || '⬇️' }}

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo
          coverage: none

      - name: Install dependencies
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--no-cache --with=phpunit/phpunit:${{ matrix.phpunit }}"

      - name: Installed dependencies
        run: |
          composer show -D

      - name: Execute tests
        run: vendor/bin/phpunit
